### ISSUE TITLE
Null deference

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [microsoft/jericho#27]
There is no check for the failed malloc

https://github.com/microsoft/jericho/blob/c58e987ede93f36738f547a734465f67bd61e273/frotz/src/blorb/blorblib.c#L104
This in turn would cause a segfault， when buff is dereferenced
https://github.com/microsoft/jericho/blob/c58e987ede93f36738f547a734465f67bd61e273/frotz/src/blorb/blorblib.c#L129

**Comment by mhauskn** [comment]
The blorblib is not used as none of the Jericho supported games are in blorb format.
