### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by nikisix** [microsoft/jericho#29]
What command are you guys using to run tests? Might want to add that to the Readme.md as well

So far, I've just tried:
```
(default) jericho ➤ python -m unittest tests

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

**Comment by MarcCote** [comment]
Thanks for the feedback. We use `nosetests`.
See https://github.com/microsoft/jericho/blob/master/.travis/test.sh#L9
