### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by MarcCote** [microsoft/jericho#31]
I'm wondering how much work would it be to add Windows support to Jericho?

For instance, we would need to de/allocate the frotz library according to the current OS (see https://github.com/microsoft/TextWorld/issues/146#issuecomment-596402900).

Also, we would need to make sure we can build the frotz library as DLL (or something).

**Comment by mhauskn** [comment]
Good question - I honestly haven't done enough windows programming to understand the scope of this work. It would be great to consult with someone with more expertise.
