### ISSUE TITLE
linker issue: multiple definition of - first defined here

### ISSUE THREAD

**Issue by MathieuTuli** [microsoft/jericho#44]
I'm having difficulty installing jericho, a dependency I need for TextWorld. Specifically, I'm having trouble building that `frotz` library. `cd`-ing into the frotz directory and running `make library -j4` gives this linker error:
```
    /usr/bin/ranlib src/ztools.a
    /usr/bin/ld: src/dumb/dumb_input.o:(.bss+0xa8): multiple definition of `do_more_prompts'; src/dumb/dumb_init.o:(.bss+0xa8): first defined here
    /usr/bin/ld: src/dumb/dumb_input.o:(.bss+0x0): multiple definition of `f_setup'; src/dumb/dumb_init.o:(.bss+0x0): first defined here
    /usr/bin/ld: src/dumb/dumb_output.o:(.bss+0x0): multiple definition of `f_setup'; src/dumb/dumb_init.o:(.bss+0x0): first defined here
    /usr/bin/ld: src/dumb/dumb_output.o:(.bss+0xa8): multiple definition of `do_more_prompts'; src/dumb/dumb_init.o:(.bss+0xa8): first defined here
    /usr/bin/ld: src/dumb/dumb_pic.o:(.bss+0x0): multiple definition of `f_setup'; src/dumb/dumb_init.o:(.bss+0x0): first defined here
    /usr/bin/ld: src/dumb/dumb_pic.o:(.bss+0xa8): multiple definition of `do_more_prompts'; src/dumb/dumb_init.o:(.bss+0xa8): first defined here
    /usr/bin/ld: src/dumb/dumb_blorb.o:(.bss+0x40): multiple definition of `f_setup'; src/dumb/dumb_init.o:(.bss+0x0): first defined here
    /usr/bin/ld: src/dumb/dumb_blorb.o:(.bss+0xe8): multiple definition of `do_more_prompts'; src/dumb/dumb_init.o:(.bss+0xa8): first defined here
```
For reference:
- running `5.12.8-arch1-1`
- `gcc --version = gcc (GCC) 11.1.0`
- `make --version = GNU Make 4.3`
- I have all required packages installed

I have attempted to do the following in an attempt to resolve this:
- downgrading to different `gcc` and `make` versions, with no success there. I only downgraded to `gcc-7` and `gcc-8`
- resolving definitions in code by including various `extern` decorators. I reached a state of the code that allowed me to compile, but then I ran it with TextWorld and the game crashed and it couldn't find the variable definitions. So basically I couldn't successfully alter the code to find this issue. I didn't do an extensive code read/fix though, and my `C` is a little rusty. This is super hacky and it makes sense why it fails to run properly.
- Downgrading to different versions of Jericho. This linker issue persists for all versions as far as I can tell

Is this an issue that others have encountered or is there something about my system that is causing this that I can fix?

Thanks

**Comment by mhauskn** [comment]
Since much of the code in Jericho is built on an older version of the Frotz engine, I'm curious if you can download Frotz (https://gitlab.com/DavidGriffith/frotz) and run "make dumb". If this works than perhaps comparing files that caused the linker error may give some insight.

**Comment by MathieuTuli** [comment]
oh I didn't realize frotz was a seperate package, I'll try that thanks!

**Comment by MathieuTuli** [comment]
okay I've fixed the issue, I was on track earlier, it had to do with missing `extern` decorators, although I initially added one too many. I've corrected that according to the update `frotz` code you sent me. I'm happy to make a PR.

**Comment by mhauskn** [comment]
Awesome! Please send a PR.
