### ISSUE TITLE
'load_bindings()' and action generation grammar parsing error

### ISSUE THREAD

**Issue by lazyrenee** [microsoft/jericho#46]
Hi there,

I was trying to generating the action by following the [doc's example](https://jericho-py.readthedocs.io/en/latest/template_action_generator.html?highlight=bindings#jericho.template_action_generator.TemplateActionGenerator.generate_actions).

It looks like the `jericho.load_bindings()` doesn't work anymore, and has been changed to `_load_bindings()`[code](https://github.com/microsoft/jericho/blob/master/jericho/jericho.py#L312). 

However, when I try with `jericho._load_bindings()`, I got another error with the dictionary parsing `KeyError: 'grammar'`

I'm assuming the text-game dictionary follows the pattern as suggested [here](https://github.com/microsoft/jericho/blob/master/jericho/jericho.py#L317-L322), not quite sure what might be wrong with my action generation. Or there might be a new version of the text-games? 

Below are my light-testing codes and errors for reference:
```
from jericho import *
from jericho.template_action_generator import TemplateActionGenerator

bindings = jericho._load_bindings('z-machine-games-master/jericho-game-suite/zork1.z5')
act_gen = TemplateActionGenerator(bindings)
interactive_objs = ['phone', 'keys', 'wallet']
act_gen.generate_actions(interactive_objs)
```
`  File "/Users/reneejia/opt/anaconda3/lib/python3.7/site-packages/jericho/template_action_generator.py", line 32, in __init__
    grammar = rom_bindings['grammar'].split(';')
KeyError: 'grammar'`

Thanks in advance!

**Comment by MarcCote** [comment]
Good catch. We need to update the documentation. Can you try to load the game first, then access the bindings?

```python
from jericho import *
from jericho.template_action_generator import TemplateActionGenerator

# Instantiate the `FrotzEnv` environment with a game.
env = jericho.FrotzEnv('z-machine-games-master/jericho-game-suite/zork1.z5')
bindings = env.bindings

act_gen = TemplateActionGenerator(bindings)
interactive_objs = ['phone', 'keys', 'wallet']
act_gen.generate_actions(interactive_objs)
```

**Comment by MarcCote** [comment]
Also, for convenience we added the attribute `act_gen` to the `FrotzEnv` object.
```python
env.act_gen  # Which correspond to `act_gen = TemplateActionGenerator(bindings)`
```

**Comment by lazyrenee** [comment]
Thanks for the quick reply and the fixes, very much appreciated! It worked for me.
