### ISSUE TITLE
How to get possible actions at each step?

### ISSUE THREAD

**Issue by IssamLaradji** [microsoft/jericho#59]
How do I get the possible actions at each step? the `admissible_actions` is `None` when I use this object class

```
infos = EnvInfos(
            inventory=True,
            description=True,
            admissible_commands=True,
            intermediate_reward=True,
            command_templates=True,
            score=True,
            max_score=True,
            extras=["walkthrough"],
        )
```

**Comment by mhauskn** [comment]
Please refer to the quickstart at https://jericho-py.readthedocs.io/en/latest/tutorial_quick.html#getting-valid-actions

**Comment by MarcCote** [comment]
@IssamLaradji the `EnvInfos.admissible_commands` only works for games generated with TextWorld. Is that your case?

**Comment by MarcCote** [comment]
Hi @IssamLaradji any progress on this?

**Comment by IssamLaradji** [comment]
Sorry for the late reply! it worked when we used FrostzEnv. Cheers.
