### ISSUE TITLE
Dictionary errors on MacOS Monterey

### ISSUE THREAD

**Issue by Sirius79** [microsoft/jericho#62]
I am having issues running some of the methods like `env.get_dictionary()` and `env.get_valid_actions()`.
Both of them are giving the error: **Error: Word count doesn't match dictionary size!**

This is the code snippet I'm using:
```
  from jericho import *

  env = FrotzEnv("../roms/jericho-game-suite/zork1.z5")
  initial_observation, info = env.reset()
  valid_actions = env.get_valid_actions()
  vocab = env.get_dictionary()
```

**Setup**

- Python 3.9.12 (using miniconda)
- MacOS Monterey (12.6)
- Jericho 3.1.0

Can you please help me figure out if I'm missing anything here?

**Comment by MarcCote** [comment]
Thanks for reporting this. What version of spacy do you have installed?

**Comment by MarcCote** [comment]
Never mind, the error comes from the ztools code (nothing to do with spacy). Here https://github.com/microsoft/jericho/blob/master/frotz/src/ztools/showdict.c#L71-L75

I don't have access to a Mac right now but I've tested your code example on Python 3.9.15, Linux and it works fine. I assume it's something related to MacOS (or your C compiler).

**Comment by Sirius79** [comment]
Understood. I also tried following the solution in #40 but that didn't help.

For now, I have commented out https://github.com/microsoft/jericho/blob/8637c21df1c75672842d521bb21be643bc8b18a3/frotz/src/ztools/showdict.c#L73-L74

Thanks for your help!

**Comment by MarcCote** [comment]
@Sirius79 can you try printing the value for `dict_size` and `word_count` for zork1.z5 ?

**Comment by Sirius79** [comment]
@MarcCote I'm getting the following values:

`word_count`: 697
`dict_size`: 83397896

**Comment by MarcCote** [comment]
Ok, that's seems problematic. What's the output of 
```
  from jericho import *

  env = FrotzEnv("../roms/jericho-game-suite/zork1.z5")
  print(env.frotz_lib.get_dictionary_word_count("../roms/jericho-game-suite/zork1.z5"))
```
?

**Comment by Sirius79** [comment]
Getting the following error for the last line:

`ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type`

**Comment by MarcCote** [comment]
Opps, try this.
```
  from jericho import *
  env = FrotzEnv("../roms/jericho-game-suite/zork1.z5")
  print(env.frotz_lib.get_dictionary_word_count(env.story_file))
```

**Comment by Sirius79** [comment]
This prints 697

**Comment by MarcCote** [comment]
Ok that's interesting. Can you try changing this line
https://github.com/microsoft/jericho/blob/master/jericho/jericho.py#L333
from 
```
frotz_lib.get_dictionary.argtypes = [POINTER(DictionaryWord)]
```
to
```
frotz_lib.get_dictionary.argtypes = [POINTER(DictionaryWord), c_int]
```

**Comment by MarcCote** [comment]
Awesome! Do you mind making a PR for it. I'll merge it and make a release later today.

**Comment by MarcCote** [comment]
The main branch should work now.

**Comment by Sirius79** [comment]
Thanks for the quick fix!
